name: Rust

on:
  workflow_call:
    inputs:
      test-runs-on:
        description: "The runner type which the test job runs on"
        required: false
        default: ubuntu-latest
        type: string
      test-container:
        description: "The container configuration for the test job, in JSON"
        required: false
        default: "null"
        type: string
      test-pre:
        description: "Command to run before tests are executed, useful for installing system deps"
        required: false
        default: ""
        type: string
      test-cargo-flags:
        description: "Additional flags to pass to cargo commands in the test step, useful for specifying features"
        required: false
        default: ""
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check
  clippy:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run: cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
  test:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    runs-on: ${{ inputs.test-runs-on }}
    container: ${{ fromJSON(inputs.test-container) }}
    steps:
      - name: Run pre script
        run: ${{ inputs.test-runs-on }}
        if: ${{ inputs.test.runs-on != '' }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --verbose ${{ inputs.test-cargo-flags }}

      - name: Run tests
        run: cargo test --verbose ${{ inputs.test-cargo-flags }}
