name: Rust
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      test-runs-on:
        description: "The runner type which the test job runs on"
        required: false
        default: ubuntu-latest
        type: string
      test-container:
        description: "The container configuration for the test job, in JSON"
        required: false
        default: "null"
        type: string
      test-pre:
        description: "Command to run before tests are executed, useful for installing system deps"
        required: false
        default: ""
        type: string
      test-cargo-flags:
        description: "Additional flags to pass to cargo commands in the test step, useful for specifying features"
        required: false
        default: ""
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # v1.94.1
        with:
          toolchain: stable
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check
  clippy:
    permissions:
      security-events: write
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # v1.94.1
        with:
          toolchain: stable
          components: clippy

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run: cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4.35.2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
  test:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    runs-on: ${{ inputs.test-runs-on }}
    container: ${{ fromJSON(inputs.test-container) }}
    steps:
      - name: Run pre script
        run: ${{ inputs.test-pre }}
        if: ${{ inputs.test-pre != '' }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # v1.94.1
        with:
          toolchain: stable

      - name: Fetch
        run: cargo fetch --locked

      - name: Build
        run: cargo build --verbose --frozen ${{ inputs.test-cargo-flags }}

      - name: Run tests
        run: cargo test --verbose ${{ inputs.test-cargo-flags }}
