name: Rust
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      test-runs-on:
        description: "The runner type which the test job runs on"
        required: false
        default: ubuntu-latest
        type: string
      test-container:
        description: "The container configuration for the test job, in JSON"
        required: false
        default: "null"
        type: string
      test-pre:
        description: "Command to run before tests are executed, useful for installing system deps"
        required: false
        default: ""
        type: string
      test-cargo-flags:
        description: "Additional flags to pass to cargo commands in the test step, useful for specifying features"
        required: false
        default: ""
        type: string
      test-riscv-rva23:
        description: "Whether to compile the tests and release binaries for RISC-V RVA23"
        required: false
        default: false
        type: boolean

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  rustfmt:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # v1.94.1
        with:
          toolchain: stable
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check
  clippy:
    permissions:
      security-events: write
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # v1.94.1
        with:
          toolchain: stable
          components: clippy

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run: cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
        env:
          CARGO_TERM_VERBOSE: false

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
  test:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    runs-on: ${{ inputs.test-runs-on }}
    container: ${{ fromJSON(inputs.test-container) }}
    steps:
      - name: Run pre script
        run: ${{ inputs.test-pre }}
        if: ${{ inputs.test-pre != '' }}

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # v1.94.1
        with:
          toolchain: stable

      - name: Fetch
        run: cargo fetch --locked

      - name: Build
        run: cargo build --frozen ${{ inputs.test-cargo-flags }}

      - name: Run tests
        run: cargo test ${{ inputs.test-cargo-flags }}

  test-riscv-rva23:
    if: inputs.test-riscv-rva23 && ((github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Cache Rust dependencies and build artifacts
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build image
        run: podman build -t odorobo-builder:rva23 .

      - name: Build binaries
        run: podman run --rm -v ${{ github.workspace }}:/code -w /code odorobo-builder:rva23 cargo build --release --verbose

      - name: Upload artifact - agent
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          name: odorobo-agent-riscv_rva23
          path: target/riscv64a23-unknown-linux-gnu/release/odorobo-agent

      - name: Upload artifact - odoroboctl
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          name: odoroboctl-riscv_rva23
          path: target/riscv64a23-unknown-linux-gnu/release/odoroboctl

      - name: Build tests
        run: podman run --rm -v ${{ github.workspace }}:/code -w /code odorobo-builder:rva23 cargo test --verbose --no-run
